In [44]:
import pandas as pd

In [45]:
df_origin = pd.read_csv('../data/E0.csv')

df_origin.head(10)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
5,E0,14/08/2021,15:00,Leicester,Wolves,1,0,H,1,0,...,1.79,-0.75,2.02,1.91,2.01,1.92,2.05,1.95,1.99,1.89
6,E0,14/08/2021,15:00,Watford,Aston Villa,3,2,H,2,0,...,1.74,0.25,2.02,1.91,2.04,1.89,2.04,1.93,1.99,1.90
7,E0,14/08/2021,17:30,Norwich,Liverpool,0,3,A,0,1,...,2.48,1.25,1.85,2.08,1.85,2.09,2.03,2.10,1.88,2.01
8,E0,15/08/2021,14:00,Newcastle,West Ham,2,4,A,2,1,...,1.95,0.25,2.01,1.92,2.02,1.91,2.12,1.94,2.00,1.89
9,E0,15/08/2021,16:30,Tottenham,Man City,1,0,H,0,0,...,1.99,1.00,1.84,2.09,1.87,2.06,1.94,2.15,1.84,2.05

In [46]:
print(list(df_origin.columns.tolist()))

['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'B365>2.5', 'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'B365AHH', 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA', 'IWCH', 'IWCD', 'IWCA', 'PSCH', 'PSCD', 'PSCA', 'WHCH', 'WHCD', 'WHCA', 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA']

In [47]:
keepcols = ['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']

df = df_origin[keepcols]

df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,3,4,12,8,2,5,0,0,0,0
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,8,3,11,9,5,4,1,2,0,0
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,3,8,10,7,7,6,2,1,0,0
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,6,1,15,11,5,2,0,0,0,0
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,6,3,13,15,6,8,2,0,0,0

In [48]:
def homepoints(FTR):
    if FTR == 'H':
        return 3
    if FTR == 'D':
        return 1
    if FTR == 'A':
        return 0
    return 0

def awaypoints(FTR):
    if FTR == 'A':
        return 3
    if FTR == 'D':
        return 1
    if FTR == 'H':
        return 0
    return 0


df2 = df.copy()
df2.loc[:, 'HomePoints'] = df.loc[:, 'FTR'].apply(homepoints)
df2.loc[:, ('AwayPoints')] = df.loc[:, ('FTR')].apply(awaypoints)
df2.loc[:, 'Score'] = df['FTHG'].astype(str) + '-' + df['FTAG'].astype(str)

df2.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AF,HC,AC,HY,AY,HR,AR,HomePoints,AwayPoints,Score
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,8,2,5,0,0,0,0,3,0,2-0
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,9,5,4,1,2,0,0,3,0,5-1
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,7,7,6,2,1,0,0,0,3,1-2
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,11,5,2,0,0,0,0,3,0,3-0
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,15,6,8,2,0,0,0,3,0,3-1

In [49]:
df2['Date'] = pd.to_datetime(df2['Date']).dt.date
print(df2['Date'].dtype)
df2.head(10)

object

c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/08/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '14/08/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15/08/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '21/08/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '22/08/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '23/08/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '28/08/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '29/08/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/09/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '17/09/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '18/09/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19/09/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '25/09/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '26/09/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '27/09/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '16/10/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '17/10/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '18/10/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '22/10/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '23/10/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '24/10/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '30/10/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '31/10/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '20/11/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '21/11/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '27/11/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '28/11/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '30/11/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '14/12/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15/12/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '16/12/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '18/12/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19/12/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '26/12/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '27/12/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '28/12/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '29/12/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '30/12/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '14/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '16/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '18/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '21/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '22/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '23/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/02/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15/02/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19/02/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '20/02/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '23/02/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '24/02/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '25/02/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '26/02/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '27/02/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/03/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '14/03/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '16/03/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '17/03/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '18/03/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\2006431\OneDrive - EY\70-Dev\01-Projects\nufcDashboard\.venv\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19/03/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AF,HC,AC,HY,AY,HR,AR,HomePoints,AwayPoints,Score
0,E0,2021-08-13,20:00,Brentford,Arsenal,2,0,H,1,0,...,8,2,5,0,0,0,0,3,0,2-0
1,E0,2021-08-14,12:30,Man United,Leeds,5,1,H,1,0,...,9,5,4,1,2,0,0,3,0,5-1
2,E0,2021-08-14,15:00,Burnley,Brighton,1,2,A,1,0,...,7,7,6,2,1,0,0,0,3,1-2
3,E0,2021-08-14,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,11,5,2,0,0,0,0,3,0,3-0
4,E0,2021-08-14,15:00,Everton,Southampton,3,1,H,0,1,...,15,6,8,2,0,0,0,3,0,3-1
5,E0,2021-08-14,15:00,Leicester,Wolves,1,0,H,1,0,...,10,5,4,1,2,0,0,3,0,1-0
6,E0,2021-08-14,15:00,Watford,Aston Villa,3,2,H,2,0,...,13,2,4,3,1,0,0,3,0,3-2
7,E0,2021-08-14,17:30,Norwich,Liverpool,0,3,A,0,1,...,14,3,11,1,1,0,0,0,3,0-3
8,E0,2021-08-15,14:00,Newcastle,West Ham,2,4,A,2,1,...,3,7,6,1,0,0,0,0,3,2-4
9,E0,2021-08-15,16:30,Tottenham,Man City,1,0,H,0,0,...,8,3,11,2,1,0,0,3,0,1-0

In [50]:
# df2.pivot_table(index=['HomeTeam'], columns='AwayTeam', values='Score', fill_value='-', aggfunc='first')

In [51]:
def homeleague(x):
        results = {
            'HomePoints': x['HomePoints'].sum(),
            'HomeWins': x[x['FTR']== 'H']['HomeTeam'].count(),
            'HomeDraws': x[x['FTR']== 'D']['HomeTeam'].count(),
            'HomeLoss': x[x['FTR']== 'A']['HomeTeam'].count(),
            'HomeGoalsFor': x['FTHG'].sum(),
            'HomeGoalsAgainst': x['FTAG'].sum(),
            'HomeGoalsDiff': x['FTHG'].sum() - x['FTAG'].sum()
        }
        return pd.Series(results)

def awayleague(x):
    results = {
        'AwayPoints': x['AwayPoints'].sum(),
        'AwayWins': x[x['FTR']== 'A']['AwayTeam'].count(),
        'AwayDraws': x[x['FTR']== 'D']['AwayTeam'].count(),
        'AwayLoss': x[x['FTR']== 'H']['AwayTeam'].count(),
        'AwayGoalsFor': x['FTAG'].sum(),
        'AwayGoalsAgainst': x['FTHG'].sum(),
        'AwayGoalsDiff': x['FTAG'].sum() - x['FTHG'].sum()
    }
    return pd.Series(results)

df_homeleague = df2.groupby('HomeTeam').apply(homeleague)
df_awayleague = df2.groupby('AwayTeam').apply(awayleague)
df_league_temp = pd.merge(df_homeleague, df_awayleague, left_index=True, right_index=True)

df_league_temp.head(20)

,HomePoints,HomeWins,HomeDraws,HomeLoss,HomeGoalsFor,HomeGoalsAgainst,HomeGoalsDiff,AwayPoints,AwayWins,AwayDraws,AwayLoss,AwayGoalsFor,AwayGoalsAgainst,AwayGoalsDiff
HomeTeam,,,,,,,,,,,,,,
Arsenal,41,13,2,4,35,17,18,28,9,1,9,26,31,-5
Aston Villa,23,6,5,8,29,29,0,22,7,1,11,23,25,-2
Brentford,24,7,3,9,22,21,1,22,6,4,9,26,35,-9
Brighton,22,5,7,7,19,23,-4,29,7,8,4,23,21,2
Burnley,21,5,6,8,18,25,-7,14,2,8,9,16,28,-12
Chelsea,34,9,7,3,37,22,15,40,12,4,3,39,11,28
Crystal Palace,29,7,8,4,27,17,10,19,4,7,8,23,29,-6
Everton,29,9,2,8,27,25,2,10,2,4,13,16,41,-25
Leeds,18,4,6,9,19,38,-19,20,5,5,9,23,41,-18
Leicester,34,10,4,5,34,23,11,18,4,6,9,28,36,-8
Liverpool,49,15,4,0,49,9,40,43,13,4,2,45,17,28
Man City,47,15,2,2,58,15,43,46,14,4,1,41,11,30
Man United,35,10,5,4,32,22,10,23,6,5,8,25,35,-10
Newcastle,30,8,6,5,26,27,-1,19,5,4,10,18,35,-17
Norwich,12,3,3,13,12,43,-31,10,2,4,13,11,41,-30
Southampton,25,6,7,6,23,24,-1,15,3,6,10,20,43,-23
Tottenham,40,13,1,5,38,19,19,31,9,4,6,31,21,10
Watford,8,2,2,15,17,46,-29,15,4,3,12,17,31,-14
West Ham,32,9,5,5,33,26,7,24,7,3,9,27,25,2
Wolves,24,7,3,9,20,25,-5,27,8,3,8,18,18,0

In [52]:


def league(x):
    results = {
        'Points': x['HomePoints'].sum() + x['AwayPoints'].sum(),
        'Wins': x['HomeWins'].sum() + x['AwayWins'].sum(),
        'Draws':  x['HomeDraws'].sum() + x['AwayDraws'].sum(),
        'Loss': x['HomeLoss'].sum() + x['AwayLoss'].sum(),
        'GoalsFor': x['HomeGoalsFor'].sum() + x['AwayGoalsFor'].sum(),
        'GoalsAgainst': x['HomeGoalsAgainst'].sum() + x['AwayGoalsAgainst'].sum(),
        'GoalDifference': x['HomeGoalsDiff'].sum() + x['AwayGoalsDiff'].sum()
    }
    return pd.Series(results)

df_league = df_league_temp.groupby('HomeTeam').apply(league)

df_league.sort_values(by='Points', ascending=False, inplace=True)

df_league.head(20)

,Points,Wins,Draws,Loss,GoalsFor,GoalsAgainst,GoalDifference
HomeTeam,,,,,,,
Man City,93,29,6,3,99,26,73
Liverpool,92,28,8,2,94,26,68
Chelsea,74,21,11,6,76,33,43
Tottenham,71,22,5,11,69,40,29
Arsenal,69,22,3,13,61,48,13
Man United,58,16,10,12,57,57,0
West Ham,56,16,8,14,60,51,9
Leicester,52,14,10,14,62,59,3
Brighton,51,12,15,11,42,44,-2
Wolves,51,15,6,17,38,43,-5
Newcastle,49,13,10,15,44,62,-18
Crystal Palace,48,11,15,12,50,46,4
Brentford,46,13,7,18,48,56,-8
Aston Villa,45,13,6,19,52,54,-2
Southampton,40,9,13,16,43,67,-24
Everton,39,11,6,21,43,66,-23
Leeds,38,9,11,18,42,79,-37
Burnley,35,7,14,17,34,53,-19
Watford,23,6,5,27,34,77,-43
Norwich,22,5,7,26,23,84,-61

In [53]:
# Best away results

df_away_results = df_league_temp.loc[:, ('AwayPoints', 'AwayGoalsDiff')]

awaypoints = df_away_results.loc[:, ('AwayPoints')].mean()
#  average away points
print('Average away points: ', awaypoints)

# Average away goal difference
awaygoaldiff = df_away_results.loc[:, ('AwayGoalsDiff')].mean()
print('Average away goal difference: ', awaygoaldiff)

# filter away teams with more than 2 points
df_away_results = df_away_results[(df_away_results['AwayPoints'] > awaypoints) & (df_away_results['AwayGoalsDiff'] > awaygoaldiff)]

df_away_results.sort_values(by='AwayPoints', ascending=False, inplace=True)
df_away_results.head(10)

Average away points:  23.75
Average away goal difference:  -3.95

           AwayPoints  AwayGoalsDiff
HomeTeam
Man City           46             30
Liverpool          43             28
Chelsea            40             28
Tottenham          31             10
Brighton           29              2
Wolves             27              0
West Ham           24              2

In [54]:
# get last 5 results for home teams
team = 'Newcastle'

df_newcastle = df2.query("(HomeTeam == @team) or (AwayTeam == @team)")

df_newcastle.head(38)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AF,HC,AC,HY,AY,HR,AR,HomePoints,AwayPoints,Score
8,E0,2021-08-15,14:00,Newcastle,West Ham,2,4,A,2,1,...,3,7,6,1,0,0,0,0,3,2-4
11,E0,2021-08-21,15:00,Aston Villa,Newcastle,2,0,H,1,0,...,18,3,4,3,4,0,0,3,0,2-0
23,E0,2021-08-28,15:00,Newcastle,Southampton,2,2,D,0,0,...,6,4,4,3,3,0,0,1,1,2-2
34,E0,2021-11-09,15:00,Man United,Newcastle,4,1,H,1,0,...,2,7,3,1,0,0,0,3,0,4-1
40,E0,2021-09-17,20:00,Newcastle,Leeds,1,1,D,1,1,...,11,4,5,2,2,0,0,1,1,1-1
55,E0,2021-09-25,15:00,Watford,Newcastle,1,1,D,0,1,...,12,5,6,4,3,0,0,1,1,1-1
64,E0,2021-02-10,15:00,Wolves,Newcastle,2,1,H,1,1,...,5,0,4,0,2,0,0,3,0,2-1
78,E0,2021-10-17,16:30,Newcastle,Tottenham,2,3,A,1,3,...,4,2,9,4,1,1,0,0,3,2-3
82,E0,2021-10-23,15:00,Crystal Palace,Newcastle,1,1,D,0,0,...,9,3,7,3,4,0,0,1,1,1-1
94,E0,2021-10-30,15:00,Newcastle,Chelsea,0,3,A,0,0,...,12,0,2,3,2,0,0,0,3,0-3
105,E0,2021-06-11,17:30,Brighton,Newcastle,1,1,D,1,0,...,10,2,5,3,4,1,0,1,1,1-1
113,E0,2021-11-20,15:00,Newcastle,Brentford,3,3,D,2,2,...,11,8,2,2,2,0,0,1,1,3-3
120,E0,2021-11-27,12:30,Arsenal,Newcastle,2,0,H,0,0,...,12,4,4,1,3,0,0,3,0,2-0
129,E0,2021-11-30,19:30,Newcastle,Norwich,1,1,D,0,0,...,11,2,5,0,0,0,1,1,1,1-1
140,E0,2021-04-12,15:00,Newcastle,Burnley,1,0,H,1,0,...,9,10,3,1,1,0,0,3,0,1-0
156,E0,2021-12-12,14:00,Leicester,Newcastle,4,0,H,1,0,...,16,4,6,2,3,0,0,3,0,4-0
164,E0,2021-12-16,20:00,Liverpool,Newcastle,3,1,H,2,1,...,4,11,0,1,3,0,0,3,0,3-1
166,E0,2021-12-19,14:00,Newcastle,Man City,0,4,A,0,2,...,6,3,6,1,2,0,0,0,3,0-4
175,E0,2021-12-27,20:00,Newcastle,Man United,1,1,D,1,0,...,8,2,4,3,3,0,0,1,1,1-1
195,E0,2022-01-15,15:00,Newcastle,Watford,1,1,D,0,0,...,13,4,6,3,2,0,0,1,1,1-1
207,E0,2022-01-22,15:00,Leeds,Newcastle,0,1,A,0,0,...,9,6,7,4,2,0,0,0,3,0-1
215,E0,2022-08-02,19:45,Newcastle,Everton,3,1,H,1,1,...,13,6,2,2,3,0,0,3,0,3-1
230,E0,2022-02-13,14:00,Newcastle,Aston Villa,1,0,H,1,0,...,15,3,6,3,4,0,0,3,0,1-0
234,E0,2022-02-19,12:30,West Ham,Newcastle,1,1,D,1,1,...,7,3,7,3,3,0,0,1,1,1-1
250,E0,2022-02-26,15:00,Brentford,Newcastle,0,2,A,0,2,...,7,6,6,3,1,1,0,0,3,0-2
260,E0,2022-05-03,15:00,Newcastle,Brighton,2,1,H,2,0,...,10,4,7,1,1,0,0,3,0,2-1
268,E0,2022-10-03,19:30,Southampton,Newcastle,1,2,A,1,1,...,7,12,5,1,1,0,0,0,3,1-2
274,E0,2022-03-13,14:00,Chelsea,Newcastle,1,0,H,0,0,...,16,7,2,4,3,0,0,3,0,1-0
283,E0,2022-03-17,19:45,Everton,Newcastle,1,0,H,0,0,...,11,5,7,2,1,1,0,3,0,1-0
296,E0,2022-03-04,16:30,Tottenham,Newcastle,5,1,H,1,1,...,7,2,3,2,3,0,0,3,0,5-1
299,E0,2022-08-04,20:00,Newcastle,Wolves,1,0,H,0,0,...,13,1,2,1,1,0,0,3,0,1-0
313,E0,2022-04-17,14:15,Newcastle,Leicester,2,1,H,1,1,...,10,3,5,2,2,0,0,3,0,2-1
318,E0,2022-04-20,19:45,Newcastle,Crystal Palace,1,0,H,1,0,...,12,2,5,1,1,0,0,3,0,1-0
324,E0,2022-04-23,15:00,Norwich,Newcastle,0,3,A,0,2,...,10,2,3,0,2,0,0,0,3,0-3
332,E0,2022-04-30,12:30,Newcastle,Liverpool,0,1,A,0,1,...,11,0,6,1,3,0,0,0,3,0-1
351,E0,2022-08-05,16:30,Man City,Newcastle,5,0,H,2,0,...,11,8,2,1,3,0,0,3,0,5-0
365,E0,2022-05-16,20:00,Newcastle,Arsenal,2,0,H,0,0,...,8,12,8,0,3,0,0,3,0,2-0
373,E0,2022-05-22,16:00,Burnley,Newcastle,1,2,A,0,1,...,9,8,2,1,0,0,0,0,3,1-2

In [57]:

def form(x):
    if x['HomeTeam'] == 'Newcastle' and x['FTR'] == 'H':
        return 'W'
    if x['AwayTeam'] == 'Newcastle' and x['FTR'] == 'A':
        return 'W'
    if x['HomeTeam'] == 'Newcastle' and x['FTR'] == 'A':
        return 'L'
    if x['AwayTeam'] == 'Newcastle' and x['FTR'] == 'H':
        return 'L'
    if x['FTR'] == 'D':
        return 'D'
    return 'U'

df_newcastle_form = df_newcastle.loc[:, ('HomeTeam', 'AwayTeam', 'FTR')]
df_newcastle_form.loc[:, 'Form'] = df_newcastle_form.apply(form, axis=1)
df_newcastle_form.reset_index(inplace=True)

df_newcastle_form = df_newcastle_form['Form']
df_newcastle_form.tail(5)

33    W
34    L
35    L
36    W
37    W
Name: Form, dtype: object