In [29]:
import pandas as pd

In [30]:
df_origin = pd.read_csv('../data/E0.csv')

df_origin.head(10)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
5,E0,14/08/2021,15:00,Leicester,Wolves,1,0,H,1,0,...,1.79,-0.75,2.02,1.91,2.01,1.92,2.05,1.95,1.99,1.89
6,E0,14/08/2021,15:00,Watford,Aston Villa,3,2,H,2,0,...,1.74,0.25,2.02,1.91,2.04,1.89,2.04,1.93,1.99,1.90
7,E0,14/08/2021,17:30,Norwich,Liverpool,0,3,A,0,1,...,2.48,1.25,1.85,2.08,1.85,2.09,2.03,2.10,1.88,2.01
8,E0,15/08/2021,14:00,Newcastle,West Ham,2,4,A,2,1,...,1.95,0.25,2.01,1.92,2.02,1.91,2.12,1.94,2.00,1.89
9,E0,15/08/2021,16:30,Tottenham,Man City,1,0,H,0,0,...,1.99,1.00,1.84,2.09,1.87,2.06,1.94,2.15,1.84,2.05

In [31]:
print(list(df_origin.columns.tolist()))

['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'B365>2.5', 'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'B365AHH', 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA', 'IWCH', 'IWCD', 'IWCA', 'PSCH', 'PSCD', 'PSCA', 'WHCH', 'WHCD', 'WHCA', 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA']

In [32]:
keepcols = ['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']

df = df_origin[keepcols]

df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,3,4,12,8,2,5,0,0,0,0
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,8,3,11,9,5,4,1,2,0,0
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,3,8,10,7,7,6,2,1,0,0
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,6,1,15,11,5,2,0,0,0,0
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,6,3,13,15,6,8,2,0,0,0

In [33]:
def homepoints(FTR):
    if FTR == 'H':
        return 3
    if FTR == 'D':
        return 1
    if FTR == 'A':
        return 0
    return 0

def awaypoints(FTR):
    if FTR == 'A':
        return 3
    if FTR == 'D':
        return 1
    if FTR == 'H':
        return 0
    return 0

# df['HomePoints'] = df.apply(lambda row: hp(row), axis=1)
df['HomePoints'] = df['FTR'].apply(homepoints)
df['AwayPoints'] = df['FTR'].apply(awaypoints)

df.head()

C:\Users\2006431\AppData\Local\Temp\ipykernel_13084\3159938322.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['HomePoints'] = df['FTR'].apply(homepoints)
C:\Users\2006431\AppData\Local\Temp\ipykernel_13084\3159938322.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['AwayPoints'] = df['FTR'].apply(awaypoints)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,HF,AF,HC,AC,HY,AY,HR,AR,HomePoints,AwayPoints
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,12,8,2,5,0,0,0,0,3,0
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,11,9,5,4,1,2,0,0,3,0
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,10,7,7,6,2,1,0,0,0,3
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,15,11,5,2,0,0,0,0,3,0
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,13,15,6,8,2,0,0,0,3,0